Thouship/testing
Breathing-ls-Fun/Newsfeed-app pull request #16
Opened 2023-05-01 01:46 UTC by thouship

2023-05-01 03:46 UTC, stefantan18 approved these changes
Looks fine. Maybe could get rid of the .DS_Store files as those are unnecessary.

2023-05-01 03:46 UTC, stefantan18 commented on .DS_Store
Could delete this.

2023-05-01 03:46 UTC, stefantan18 commented on NewsFeedApp/.DS_Store
Could delete this.

2023-05-01 03:47 UTC, stefantan18 requested changes
Looks fine. Could get rid of the .DS_Store files.

2023-05-01 04:30 UTC, aimran1 commented
Tests look good and seem to cover all elements of the html page. Agree with Stefan, you should remove the  .DS_Store files.

2023-05-01 04:52 UTC, erchardsamoh commented
yep, the tests u've made here should cover most of the facets of the homepage. just need the article cards to be made/merged so you could make the tests for that.

2023-05-01 06:27 UTC, jjames003 commented
The genre options in the navbar don't need tests as of right now, because we have not given functionality to them. Currently, we have the NewsFeed logo, Preferences, Search, Sign Up, and Log In buttons up and functioning.

2023-05-13 03:51 UTC, erchardsamoh approved these changes
looks good now

2023-05-13 03:56 UTC, merged